### ISSUE TITLE
Cantidad de decimales en entry "D" de metodo acyrsa_cotizaciones

### ISSUE THREAD

**Issue by jfgomezok** [augustohassel/acyRsa#2]
Augus, muy bueno el paquete!

Fijate que el metodo acyrsa_cotizaciones para el entry "D" de subyacentes del RFX20 está truncando en algún lado los decimales. Por API viajan bien, en la respuesta del método de R se truncan!

`df <- acyRsa::acyrsa_cotizaciones(
    connection = conn,
    entry_type = "D",
    date       = as.Date(Sys.Date())
  )`

Resultado: 
`> df$MDEntrySize`
` [1]  64.3911  16.3812  18.0126   6.0809  85.1530 201.3351  25.0133  30.4015  91.5721  10.6353   2.6044  96.9979  23.5753
[14]   4.0698   7.0245  26.0979  16.8304 102.6857  67.1905  15.3298`

**Comment by augustohassel** [comment]
Juan Fra!
Ahí subí una nueva versión que entiendo soluciona el problema por el cual se estaba truncando el número. 
Abrazo!
