### ISSUE TITLE
Agregar parametro "Projected" a la query

### ISSUE THREAD

**Issue by jfgomezok** [augustohassel/acyRsa#3]
Augus, ¿se puede agregar el parámetro "projected" al metodo de cotizaciones?

En un boolean TRUE/FALSE y sirve para traer la cartera proyectada en vez de la vigente (todo para el entry "D").

Adjunto foto.
![image](https://user-images.githubusercontent.com/50673376/90545410-fd3c8a00-e15e-11ea-8ee1-d15978f4db98.png)

Saludos!

**Comment by augustohassel** [comment]
Listo en version 0.0.0.9011. Controlalo y cerra el issue si esta OK. Faltaría agregar documentación sobre qué hace ese parámetro.

**Comment by jfgomezok** [comment]
Validado! Gracias! =)
